name: Build, Push, and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Check Docker Version
      run: docker --version

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/python-website:latest .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/python-website:latest

    - name: Deploy to Azure Container Instances
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az container create \
            --resource-group Container_gp \
            --name python-website-container \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/python-website:latest \
            --cpu 1 \
            --memory 1.5 \
            --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label pythonwebsite \
            --ports 80
